// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Project struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Language   sql.NullString `json:"language"`
	Length     sql.NullInt32  `json:"length"`
	Transcript sql.NullString `json:"transcript"`
	TeamID     int64          `json:"team_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Role struct {
	ID        int64        `json:"id"`
	Role      string       `json:"role"`
	UserID    int64        `json:"user_id"`
	TeamID    int64        `json:"team_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Team struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID         int64        `json:"id"`
	Email      string       `json:"email"`
	Password   string       `json:"password"`
	LastSignin sql.NullTime `json:"last_signin"`
	CreatedAt  sql.NullTime `json:"created_at"`
}
